### ISSUE TITLE
[FEATURE] Add reader unit tests

### ISSUE THREAD

**Issue by kol-oss** [Olympus-Group/athena#13]
### Description

_Unit testing, also known as component or module testing, is a form of software testing by which isolated source code is tested to validate expected behavior._

_Unit testing describes tests that are run at the unit level to contrast testing at the integration or system level._

### To-Do:

- [x] Add valid files cases
- [x] Add invalid files cases
- [x] Add inaccessible file case
