### ISSUE TITLE
[BUG] Fix command line interface

### ISSUE THREAD

**Issue by kol-oss** [Olympus-Group/athena#17]
### To-Do:

- [x] Add `jest.config` file
- [x] Fix CLI tests
- [x] Fix code style
