### ISSUE TITLE
[FEATURE] Add continuous integration

### ISSUE THREAD

**Issue by kol-oss** [Olympus-Group/athena#19]
### Description

_Continuous integration (CI) is the practice of frequently building and testing a software system during its development. It is intended to ensure that code written by programmers is always buildable, runnable and passes automated testing. Developers merge to an integration branch and an automated system builds and tests._

### To-Do:

- [x] Add `deploy.yml` file to `.github` directory
- [x] Add dependency installation step
- [x] Add test running step
