### ISSUE TITLE
[FEATURE] Add npm project

### ISSUE THREAD

**Issue by kol-oss** [Olympus-Group/athena#2]
### Description

Initialize a npm project with basic development configuration (typescript and eslint).

### To-Do:

- [x] Add npm project
- [x] Add development tools
- [x] Add code style tools
