### ISSUE TITLE
[ENHANCEMENT] Add rule nodes

### ISSUE THREAD

**Issue by kol-oss** [Olympus-Group/athena#22]
### Description

Node is the basic cover over the rule operation with method `Run(value)` that checks if field value satisfies the conditions.

### To-Do:

- [x] Add [name] node
- [x] Add [name] node
- [x] Add [name] node
- [x] Add new nodes to `token-node` map

### Additional Notes

See the available operations on the development board.
