### ISSUE TITLE
[FEATURE] Add entry point

### ISSUE THREAD

**Issue by kol-oss** [Olympus-Group/athena#29]
### Description

We have a file `index.ts`. There you have to implement the usage of our system with CLI-input and files reading, logging and outputting the result.

### To-Do:

- [x] Add CLI usage
- [x] Add file system usage
- [x] Add lexer and parser usage
