### ISSUE TITLE
[FEATURE] Add parser and nodes unit tests

### ISSUE THREAD

**Issue by mari4kaa** [Olympus-Group/athena#35]
### Description

Your task is to fully tests `parser` with unit tests.

_Unit testing, also known as component or module testing, is a form of software testing by which isolated source code is tested to validate expected behavior._

_Unit testing describes tests that are run at the unit level to contrast testing at the integration or system level._

### To-Do:

- [x] Add tests for valid schemas
- [x] Add tests for invalid schemas
- [x] Test all Nodes on different input types
