### ISSUE TITLE
[FEATURE] Add basic lexer logic

### ISSUE THREAD

**Issue by kol-oss** [Olympus-Group/athena#7]
### Description

_In computer science, lexical analysis is the process of analytically parsing an input sequence of characters (such as source code in a programming language) to produce an output sequence of characters called "tokens" (similar to the grouping of letters in words)._

_A group of characters in an input sequence that is identified as a token at the output of a process is called a token. In the process of lexical analysis, lexemes are recognized and extracted from the input sequence of characters._

### To-Do:

Your task is to implement basic lexer and create an opportunity to extend the syntax with another tokens. You have to implement some basic token's regexp (like Field and Option), but **not implement** all the syntax.

- [x] Add lexer logic
- [x] Add token class
- [x] Add basic token types

### Additional Notes

See the syntax example on our development board.
