### ISSUE TITLE
[ENHANCEMENT] Add token types

### ISSUE THREAD

**Issue by kol-oss** [Olympus-Group/athena#8]
### Description

We have a lexer and some basic tokens with their regular expressions. Your task is to cover all the developed syntax with such tokens and corresponding regexps.

### To-Do:

- [x] Add **String** token type
- [x] Add **Bool** token type
- [x] Add **Number** token type

You can add your own custom types according to the project documentation.
