### ISSUE TITLE
[FEATURE] Add lexer unit tests

### ISSUE THREAD

**Issue by kol-oss** [Olympus-Group/athena#9]
### Description

_Unit testing, also known as component or module testing, is a form of software testing by which isolated source code is tested to validate expected behavior._

_Unit testing describes tests that are run at the unit level to contrast testing at the integration or system level._

### To-Do:

- [x] Add valid syntax cases
- [x] Add invalid syntax cases
- [x] Add different token types cases
